In [3]:
# import the library and give it a shorter name 'np'
import numpy as np

# create 100 randomly distributed numbers
X = np.random.normal(size=100)

print(X)

# transform X into a 2-dimensional array of size 20x5
X.reshape((20, 5))

# calculate the matrix dot product: X*X', where X' is the transpose of X
X.dot(X.T)

[ 1.01128475  0.18048672  0.33304353 -0.15853086  0.93664355 -1.11322025
 -0.26081599  0.2630074  -0.7245577   0.35967463  1.4152604  -0.27977878
  0.15634743  2.96661537 -1.79355531  1.59708186 -0.12095173 -1.76682068
 -0.88969115  0.55304149 -0.75649514  0.93720031  0.12446847 -0.81126729
  0.25329544 -0.62390406  1.478497    0.62904299  1.33206434  0.04097081
 -0.48774038 -1.2798883   0.1081341  -1.58332476  0.80783996 -1.36924132
  0.30888441 -1.27138039 -1.10796803  1.39567481  1.77337681  1.68486095
 -1.45580252  1.82009156 -0.68872043  0.55162257  0.98670277  0.56118989
  0.32482391  0.27643358  1.87171264 -1.04309251  1.7346973  -1.40065302
  1.80042926 -1.50120362 -1.16526239  0.70767781 -1.326766   -0.37989068
 -0.48294403  1.02298699 -0.31734285 -1.23740939 -0.00761855  3.24541549
 -1.80601647 -0.80453994  0.11502576  0.27127394  0.13005734 -0.48271409
 -0.28634992 -1.19832072 -0.04407436  0.06359648  0.8032118  -0.41052141
  0.70857881 -1.07284167 -0.76616688  0.58708636  1

114.77288819484325

In [18]:
# create 4 randomly distributed numbers
# Y = np.random.normal(size=4)

# create 4 incremental numbers
Y = np.array([1, 2, 3, 4])
print(Y)

# transform Y into a 2-dimensional array of size 2x2
# -> happens in-place and does nothing here -> output to variable Y_ for further use
Y_ = Y.reshape((2, 2))
print(Y_)
YT = Y_.transpose()
print(YT)

# calculate the matrix dot product: Y*Y', where Y' is the transpose of Y
Y.dot(Y.T)
# -> = 1x1 + 2x2 + 3x3 + 4x4
# -> a1xb1 + a2xb2 + a3xb3 + a4xb4 + ...

[1 2 3 4]
[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


30